- name: Setup servers
  hosts: all
  become: true

  vars:
    pip_install_packages: "{{ packages }}"

  tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install pip
      ansible.builtin.include_role:
        name: geerlingguy.pip

    - name: Create env env_file
      ansible.builtin.template:
        src: templates/.env.j2
        dest: "{{ env_file_path }}"
        mode: '0644'

    - name: Create a network
      community.docker.docker_network:
        name: "{{ network_name }}"

    - name: Start a redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine:5.0.3-alpine3.15
        env_file: "{{ env_file_path }}"
        restart_policy: always
        ports:
          - 3000:3000
        networks:
          - name: "{{ network_name }}"
